# Generated by Django 5.2.7 on 2025-10-04 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards_app', '0003_task_created_at_task_due_date_task_reviewer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.CharField(max_length=50),
        ),
    ]
